import { Met } from './nutrition-model';

export const idealWeightBmi = 22;
export const defaultProteinDemand = 2;
export const KALORIES = {
  light: 5,
  medium: 10,
  hard: 15,
};

export const BASIC_DATA_KEY = 'ndc-basicData';
export const PAL_DATA_KEY = 'ndc-palData';
export const SPORT_DATA_KEY = 'ndc-sportData';
export const NUTRITION_DATA_KEY = 'ndc-nutritionData';
export const BASIC_EDIT_KEY = 'ndc-basicShowEdit';
export const PAL_EDIT_KEY = 'ndc-palShowEdit';
export const SPORT_EDIT_KEY = 'ndc-sportShowEdit';

export const MET_DATA: Met[] = [
  { name: 'Schlafen', value: 0.95, key: 'Schlafen' },
  { name: 'Sich ausruhen', value: 1.0, key: 'Sich_ausruhen' },
  { name: 'Sitzen/Liegen', value: 1.2, key: 'Sitzen_Liegen' },
  { name: 'Sitzen', value: 1.4, key: 'Sitzen' },
  { name: 'Schreibtischarbeit', value: 1.5, key: 'Schreibtischarbeit' },
  { name: 'Fahren', value: 1.6, key: 'Fahren' },
  { name: 'Stehen', value: 1.7, key: 'Stehen' },
  { name: 'Gehen langsam 3 km/h', value: 1.7, key: 'Gehen_langsam_3_km_h' },
  { name: 'Golf', value: 2.0, key: 'Golf' },
  { name: 'Musik machen', value: 2.0, key: 'Musik_machen' },
  { name: 'Einkaufen', value: 2.3, key: 'Einkaufen' },
  { name: 'Yoga', value: 2.5, key: 'Yoga' },
  { name: 'Gymnastik', value: 2.5, key: 'Gymnastik' },
  { name: 'Dehnübungen', value: 2.5, key: 'Dehn_bungen' },
  { name: 'Hausarbeit', value: 2.5, key: 'Hausarbeit' },
  { name: 'Angeln', value: 3.0, key: 'Angeln' },
  { name: 'Rudersport', value: 3.0, key: 'Rudersport' },
  { name: 'Kanufahren', value: 3.0, key: 'Kanufahren' },
  { name: 'Segeln', value: 3.0, key: 'Segeln' },
  { name: 'Pilates', value: 3.1, key: 'Pilates' },
  { name: 'Gehen normal 4.8 km/h', value: 3.3, key: 'Gehen_normal_4_8_km_h' },
  { name: 'Freiübungen (leicht)', value: 3.5, key: 'Frei_bungen__leicht_' },
  { name: 'Gehen schneller 5.6 km/h', value: 3.8, key: 'Gehen_schneller_5_6_km_h' },
  { name: 'Volleyball', value: 4.0, key: 'Volleyball' },
  { name: 'Schwimmen (langsam)', value: 4.0, key: 'Schwimmen__langsam_' },
  { name: 'Radfahren (gemächlich) bis 16 km/h', value: 4.0, key: 'Radfahren__gem_chlich__bis_16_km_h' },
  { name: 'Kegeln', value: 4.0, key: 'Kegeln' },
  { name: 'Bowlen', value: 4.0, key: 'Bowlen' },
  { name: 'Gartenarbeit', value: 4.0, key: 'Gartenarbeit' },
  { name: 'Reiten', value: 4.0, key: 'Reiten' },
  { name: 'Motorrad fahren', value: 4.0, key: 'Motorrad_fahren' },
  { name: 'Tanzen (langsam)', value: 4.0, key: 'Tanzen__langsam_' },
  { name: 'Bauchtanz', value: 4.2, key: 'Bauchtanz' },
  { name: 'Völkerball', value: 4.5, key: 'V_lkerball' },
  { name: 'Jagen', value: 5.0, key: 'Jagen' },
  { name: 'Badminton', value: 5.0, key: 'Badminton' },
  { name: 'Kricket', value: 5.0, key: 'Kricket' },
  { name: 'Tanzen (normal)', value: 5.0, key: 'Tanzen__normal_' },
  { name: 'Schneeräumen', value: 5.0, key: 'Schneer_umen' },
  { name: 'Eislaufen 16 hm/h', value: 5.0, key: 'Eislaufen_16_hm_h' },
  { name: 'Softball', value: 5.0, key: 'Softball' },
  { name: 'Gehen sehr zügig 6.5 Km/h', value: 5.0, key: 'Gehen_sehr_z_gig_6_5_Km_h' },
  { name: 'Konditionstraining', value: 5.5, key: 'Konditionstraining' },
  { name: 'Zumba', value: 6.0, key: 'Zumba' },
  { name: 'Radfahren (langsam) 17.7 km/h', value: 6.0, key: 'Radfahren__langsam__17_7_km_h' },
  { name: 'Crosstrainer (langsam)', value: 6.0, key: 'Crosstrainer__langsam_' },
  { name: 'Zirkeltraining', value: 6.0, key: 'Zirkeltraining' },
  { name: 'Wasserski', value: 6.0, key: 'Wasserski' },
  { name: 'Tanzen (schnell, Aerobic)', value: 6.0, key: 'Tanzen__schnell__Aerobic_' },
  { name: 'Krafttraining (mäßig)', value: 6.0, key: 'Krafttraining__m__ig_' },
  { name: 'Wandern', value: 6.0, key: 'Wandern' },
  { name: 'Basketball', value: 6.0, key: 'Basketball' },
  { name: 'Schwimmen (mäßig)', value: 7.0, key: 'Schwimmen__m__ig_' },
  { name: 'Tennis', value: 8.0, key: 'Tennis' },
  { name: 'Freiübungen (schwer)', value: 8.0, key: 'Frei_bungen__schwer_' },
  { name: 'Crosstrainer (mäßig)', value: 8.0, key: 'Crosstrainer__m__ig_' },
  { name: 'Squash', value: 8.0, key: 'Squash' },
  { name: 'Handball', value: 8.0, key: 'Handball' },
  { name: 'Radfahren (mäßig) 21 km/h', value: 8.0, key: 'Radfahren__m__ig__21_km_h' },
  { name: 'Hallenfußball', value: 8.0, key: 'Hallenfu_ball' },
  { name: 'Lacrosse', value: 8.0, key: 'Lacrosse' },
  { name: 'Fußball', value: 8.0, key: 'Fu_ball' },
  { name: 'Hockey', value: 8.0, key: 'Hockey' },
  { name: 'Laufen / Joggen 8 km/h', value: 8.0, key: 'Laufen___Joggen_8_km_h' },
  { name: 'Skifahren bergab', value: 8.0, key: 'Skifahren_bergab' },
  { name: 'Aqua Jogging (mäßig)', value: 8.5, key: 'Aqua_Jogging__m__ig_' },
  { name: 'Heimtrainder (Durchschnittswert)', value: 8.5, key: 'Heimtrainder__Durchschnittswert_' },
  { name: 'Crosstrainer schnell', value: 10.0, key: 'Crosstrainer_schnell' },
  { name: 'Rollschuh laufen', value: 10.0, key: 'Rollschuh_laufen' },
  { name: 'Radfahren (schnell) 21 km/h', value: 10.0, key: 'Radfahren__schnell__21_km_h' },
  { name: 'Racquetball', value: 10.0, key: 'Racquetball' },
  { name: 'Schwimmen (schnell)', value: 10.0, key: 'Schwimmen__schnell_' },
  { name: 'Laufen 9.7 km/h', value: 10.0, key: 'Laufen_9_7_km_h' },
  { name: 'Laufen 11 km/h', value: 11.5, key: 'Laufen_11_km_h' },
  { name: 'Boxen', value: 12.0, key: 'Boxen' },
  { name: 'Radfahren (sehr schnell) 28 km/h', value: 12.0, key: 'Radfahren__sehr_schnell__28_km_h' },
  { name: 'Skifahren (querfeldein)', value: 12.0, key: 'Skifahren__querfeldein_' },
  { name: 'Laufen 13 km/h', value: 13.5, key: 'Laufen_13_km_h' },
  { name: 'Laufen 14.5 km/h', value: 15.0, key: 'Laufen_14_5_km_h' },
  { name: 'Laufen 16 km/h', value: 16.0, key: 'Laufen_16_km_h' },
  { name: 'Aqua Jogging (schnell/schwer)', value: 16.0, key: 'Aqua_Jogging__schnell_schwer_' },
];

export const nutritionType = [
  { name: 'carnivore', value: 0.03 },
  { name: 'ketogen', value: 0.07 },
  { name: 'lowcarb', value: 0.2 },
  { name: 'normal', value: 0.4 },
  { name: 'highcarb', value: 0.6 },
  { name: 'eigeneverteilung', value: -1 },
];
